#!/bin/bash

current_workspace=$(i3-msg -t 'get_workspaces' | python -c 'import json; import sys; ws = json.load(sys.stdin); print([w["name"] for w in ws if w["focused"]][0])')
next=$(python -c 'import sys; w=int(sys.argv[1])+1; w = w if w < 11 else 1; print w' $current_workspace)

i3-msg "workspace $next"
