#!/bin/bash

# if sound is playing don't run screensaver
pacmd list-sink-inputs  | grep -w state | grep -q RUNNING && exit 0

xset dpms force standby

sleep 60
status=$(xset q | grep 'Monitor is ' | sed 's/\s*Monitor is \(.*\)$/\1/g')

if [ "$status" == "in Standby" ]; then
    i3lock -c 000000
fi
