#!/bin/bash

#alias nvim-kick="NVIM_APPNAME=kickstart nvim"

export PATH="$PATH:/opt/nvim-linux64/bin"

alias nv="NVIM_APPNAME=nvim.scratch nvim"
alias nv-chad="NVIM_APPNAME=nvim.nvchad nvim"
alias nv-lazy="NVIM_APPNAME=nvim.lazy nvim"
alias nv-astro="NVIM_APPNAME=nvim.astro nvim"

function nvims() {
  items=("default" "kickstart" "LazyVim" "NvChad" "AstroNvim")
  config=$(printf "%s\n" "${items[@]}" | fzf --prompt=" Neovim Config  " --height='10' --layout=reverse --border --exit-0)
  if [[ -z $config ]]; then
    echo "Nothing selected"
    return 0
  elif [[ $config == "default" ]]; then
    config=""
  fi
  NVIM_APPNAME=$config nvim $@
}

#bindkey -s ^a "nvims\n"
