#!/bin/bash

# pip install --user powerline-shell
# powerline-shell --generate > ~/.config/powerline-shell/config.json
# ~/.config/powerline-shell/config.json

# https://powerline.readthedocs.io/en/master/develop/segments.html#dev-segments

_update_ps1() {     PS1=$(powerline-shell $?); }
if [[ $TERM != linux && ! $PROMPT_COMMAND =~ _update_ps1 ]]; then     PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"; fi
